In [102]:
import numpy as np
import sys
if "../" not in sys.path:
    sys.path.append("../") 
from lib.envs.gridworld import GridworldEnv
import pprint

In [114]:
pp = pprint.PrettyPrinter(indent=2)

env = GridworldEnv()

In [36]:
env.P[2] # prob, next_state, reward, done

{0: [(1.0, 2, -1.0, False)],
 1: [(1.0, 3, -1.0, False)],
 2: [(1.0, 6, -1.0, False)],
 3: [(1.0, 1, -1.0, False)]}

In [108]:
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] (transition probability on state s taking action a) 
                        is a list of transition tuples (prob, next_state, reward, done).
            env.nS is a number of states in the environment. 
            env.nA is a number of actions in the environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
    
    Returns:
        Vector of length env.nS representing the value function.
    """
    # Start with a random (all 0) value function
    V = np.zeros(env.nS)
    num_iter = 0 
    
    while True:
        # TODO: Implement!
        # iterate all states
        delta = 0
        for s in range(0, len(V)):
            transit_prob = env.P[s]
            v_val = 0
            for a in transit_prob.keys(): #iterate all actions
                #act = action[0] # (prob, next_state, reward, done)
                # for prob, next_state, reward, done in act:
                #    v_val + = 
                p = transit_prob[a][0]
                pol = policy[s][a] # policy on state s to take action a
                v_val += pol  *(p[2] + discount_factor * p[0] * V[p[1]])
            
            #delta = max(delta, np.abs(v_val - V[s]))
            delta +=np.abs(v_val - V[s])
            V[s] = v_val
        
        if delta < theta:
            break
        
    return np.array(V)

In [106]:
# index of random_policy[i]: action
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policy_eval(random_policy, env)

In [109]:
print("Value Function:")
print(v)
print("")

print("Reshaped Grid Value Function:")
print(v.reshape(env.shape))
print("")

Value Function:
[  0.         -13.99993529 -19.99990698 -21.99989761 -13.99993529
 -17.9999206  -19.99991379 -19.99991477 -19.99990698 -19.99991379
 -17.99992725 -13.99994569 -21.99989761 -19.99991477 -13.99994569
   0.        ]

Reshaped Grid Value Function:
[[  0.         -13.99993529 -19.99990698 -21.99989761]
 [-13.99993529 -17.9999206  -19.99991379 -19.99991477]
 [-19.99990698 -19.99991379 -17.99992725 -13.99994569]
 [-21.99989761 -19.99991477 -13.99994569   0.        ]]



In [113]:
# Test: Make sure the evaluated policy is what we expected

expected_v = np.array([0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22, -20, -14, 0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)

In [67]:
v

array([-1., -1., -1., -1., -2., -2., -2., -2., -2., -2., -2., -2., -2.,
       -2., -2., -2.])